# Form implementation generated from reading ui file 'nxmotors.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1051, 679)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1051, 671))
        self.stackedWidget.setStyleSheet("color: rgb(14, 27, 111);\n"
"background-color: rgb(27, 34, 124);\n"
"color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(0, 0, 1051, 661))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit.setGeometry(QtCore.QRect(410, 240, 241, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 290, 241, 22))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        self.pushButton.setGeometry(QtCore.QRect(460, 360, 81, 21))
        self.pushButton.setStyleSheet("color: rgb(245, 255, 216); font-size: 10pt;\n"
"background-color: rgb(88, 155, 255);\n"
"def login(self):\n"
"    username = self.ui.lineEdit.text()\n"
"    password = self.ui.lineEdit_2.text()\n"
"\n"
"    if username == \"admin\" and password == \"1234\":\n"
"        print(\"Login Successful\")\n"
"    else:\n"
"        print(\"Incorrect username or password\")")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(270, 290, 121, 21))
        self.label_3.setStyleSheet("color: rgb(245, 255, 216); font-size: 15pt;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page)
        self.label_4.setGeometry(QtCore.QRect(290, 90, 431, 41))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(300, 50, 411, 41))
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.page)
        self.label_8.setGeometry(QtCore.QRect(770, 650, 101, 21))
        self.label_8.setStyleSheet("color: rgb(245, 255, 216); font-size: 15pt;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.page)
        self.label_9.setGeometry(QtCore.QRect(740, 660, 101, 21))
        self.label_9.setStyleSheet("color: rgb(245, 255, 216); font-size: 15pt;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.page)
        self.label_10.setGeometry(QtCore.QRect(750, 660, 101, 21))
        self.label_10.setStyleSheet("color: rgb(245, 255, 216); font-size: 15pt;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(268, 240, 131, 20))
        self.label_2.setStyleSheet("color: rgb(245, 255, 216); font-size: 15pt;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.VehicleManagement = QtWidgets.QLabel(parent=self.page_3)
        self.VehicleManagement.setGeometry(QtCore.QRect(320, 50, 401, 51))
        self.VehicleManagement.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"}")
        self.VehicleManagement.setObjectName("VehicleManagement")
        self.VehicleLineEdit = QtWidgets.QLineEdit(parent=self.page_3)
        self.VehicleLineEdit.setGeometry(QtCore.QRect(170, 180, 113, 22))
        self.VehicleLineEdit.setObjectName("VehicleLineEdit")
        self.RegistrationLabel = QtWidgets.QLabel(parent=self.page_3)
        self.RegistrationLabel.setGeometry(QtCore.QRect(650, 160, 141, 16))
        self.RegistrationLabel.setObjectName("RegistrationLabel")
        self.EnterRegistration = QtWidgets.QLineEdit(parent=self.page_3)
        self.EnterRegistration.setGeometry(QtCore.QRect(650, 180, 121, 22))
        self.EnterRegistration.setObjectName("EnterRegistration")
        self.makeLineEdit = QtWidgets.QLineEdit(parent=self.page_3)
        self.makeLineEdit.setGeometry(QtCore.QRect(170, 270, 113, 22))
        self.makeLineEdit.setObjectName("makeLineEdit")
        self.makeLabel = QtWidgets.QLabel(parent=self.page_3)
        self.makeLabel.setGeometry(QtCore.QRect(170, 250, 61, 20))
        self.makeLabel.setObjectName("makeLabel")
        self.modelLabel = QtWidgets.QLabel(parent=self.page_3)
        self.modelLabel.setGeometry(QtCore.QRect(650, 250, 71, 20))
        self.modelLabel.setObjectName("modelLabel")
        self.modelLineEdit = QtWidgets.QLineEdit(parent=self.page_3)
        self.modelLineEdit.setGeometry(QtCore.QRect(650, 270, 113, 22))
        self.modelLineEdit.setObjectName("modelLineEdit")
        self.yearLineEdit = QtWidgets.QLineEdit(parent=self.page_3)
        self.yearLineEdit.setGeometry(QtCore.QRect(170, 380, 113, 22))
        self.yearLineEdit.setObjectName("yearLineEdit")
        self.yearLabel = QtWidgets.QLabel(parent=self.page_3)
        self.yearLabel.setGeometry(QtCore.QRect(170, 360, 71, 16))
        self.yearLabel.setObjectName("yearLabel")
        self.PriceLabel = QtWidgets.QLabel(parent=self.page_3)
        self.PriceLabel.setGeometry(QtCore.QRect(650, 360, 61, 16))
        self.PriceLabel.setObjectName("PriceLabel")
        self.PriceLineEdit = QtWidgets.QLineEdit(parent=self.page_3)
        self.PriceLineEdit.setGeometry(QtCore.QRect(650, 380, 113, 22))
        self.PriceLineEdit.setObjectName("PriceLineEdit")
        self.VehicletypeLabel = QtWidgets.QLabel(parent=self.page_3)
        self.VehicletypeLabel.setGeometry(QtCore.QRect(170, 450, 131, 20))
        self.VehicletypeLabel.setObjectName("VehicletypeLabel")
        self.VehicleID_2 = QtWidgets.QLabel(parent=self.page_3)
        self.VehicleID_2.setGeometry(QtCore.QRect(170, 160, 61, 20))
        self.VehicleID_2.setObjectName("VehicleID_2")
        self.vehicleTypeComboBox = QtWidgets.QComboBox(parent=self.page_3)
        self.vehicleTypeComboBox.setGeometry(QtCore.QRect(170, 470, 75, 22))
        self.vehicleTypeComboBox.setObjectName("vehicleTypeComboBox")
        self.vehicleTypeComboBox.addItem("")
        self.vehicleTypeComboBox.addItem("")
        self.vehicleTypeComboBox.addItem("")
        self.AvailabilityLabel = QtWidgets.QLabel(parent=self.page_3)
        self.AvailabilityLabel.setGeometry(QtCore.QRect(650, 450, 91, 16))
        self.AvailabilityLabel.setObjectName("AvailabilityLabel")
        self.AvailabilityComboBox = QtWidgets.QComboBox(parent=self.page_3)
        self.AvailabilityComboBox.setGeometry(QtCore.QRect(650, 470, 75, 22))
        self.AvailabilityComboBox.setObjectName("AvailabilityComboBox")
        self.AvailabilityComboBox.addItem("")
        self.AvailabilityComboBox.addItem("")
        self.AvailabilityComboBox.addItem("")
        self.clearVehicleButton = QtWidgets.QPushButton(parent=self.page_3)
        self.clearVehicleButton.setGeometry(QtCore.QRect(360, 610, 111, 26))
        self.clearVehicleButton.setObjectName("clearVehicleButton")
        self.saveVehicleButton = QtWidgets.QPushButton(parent=self.page_3)
        self.saveVehicleButton.setGeometry(QtCore.QRect(230, 610, 111, 26))
        self.saveVehicleButton.setObjectName("saveVehicleButton")
        self.vehicleBackButton = QtWidgets.QPushButton(parent=self.page_3)
        self.vehicleBackButton.setGeometry(QtCore.QRect(500, 610, 111, 26))
        self.vehicleBackButton.setObjectName("vehicleBackButton")
        self.vehicleNextButton = QtWidgets.QPushButton(parent=self.page_3)
        self.vehicleNextButton.setGeometry(QtCore.QRect(640, 610, 141, 26))
        self.vehicleNextButton.setObjectName("vehicleNextButton")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.customerandbookingmanagement = QtWidgets.QLabel(parent=self.page_4)
        self.customerandbookingmanagement.setGeometry(QtCore.QRect(220, 20, 691, 51))
        self.customerandbookingmanagement.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"}")
        self.customerandbookingmanagement.setObjectName("customerandbookingmanagement")
        self.VehicleIDLineEdit_2 = QtWidgets.QLineEdit(parent=self.page_4)
        self.VehicleIDLineEdit_2.setGeometry(QtCore.QRect(150, 140, 113, 22))
        self.VehicleIDLineEdit_2.setObjectName("VehicleIDLineEdit_2")
        self.contactnumberLabel = QtWidgets.QLabel(parent=self.page_4)
        self.contactnumberLabel.setGeometry(QtCore.QRect(150, 300, 91, 16))
        self.contactnumberLabel.setObjectName("contactnumberLabel")
        self.fullnamelabel = QtWidgets.QLabel(parent=self.page_4)
        self.fullnamelabel.setGeometry(QtCore.QRect(150, 210, 61, 20))
        self.fullnamelabel.setObjectName("fullnamelabel")
        self.contactnumber = QtWidgets.QLineEdit(parent=self.page_4)
        self.contactnumber.setGeometry(QtCore.QRect(150, 320, 131, 22))
        self.contactnumber.setObjectName("contactnumber")
        self.VehicleID = QtWidgets.QLabel(parent=self.page_4)
        self.VehicleID.setGeometry(QtCore.QRect(150, 120, 81, 20))
        self.VehicleID.setObjectName("VehicleID")
        self.fullname = QtWidgets.QLineEdit(parent=self.page_4)
        self.fullname.setGeometry(QtCore.QRect(150, 230, 131, 22))
        self.fullname.setObjectName("fullname")
        self.Email = QtWidgets.QLineEdit(parent=self.page_4)
        self.Email.setGeometry(QtCore.QRect(150, 400, 131, 22))
        self.Email.setObjectName("Email")
        self.Emaillabel = QtWidgets.QLabel(parent=self.page_4)
        self.Emaillabel.setGeometry(QtCore.QRect(150, 380, 91, 16))
        self.Emaillabel.setObjectName("Emaillabel")
        self.BookingBackButton_2 = QtWidgets.QPushButton(parent=self.page_4)
        self.BookingBackButton_2.setGeometry(QtCore.QRect(550, 590, 111, 26))
        self.BookingBackButton_2.setObjectName("BookingBackButton_2")
        self.clearVehicleButton_2 = QtWidgets.QPushButton(parent=self.page_4)
        self.clearVehicleButton_2.setGeometry(QtCore.QRect(410, 590, 111, 26))
        self.clearVehicleButton_2.setObjectName("clearVehicleButton_2")
        self.SaveBooking = QtWidgets.QPushButton(parent=self.page_4)
        self.SaveBooking.setGeometry(QtCore.QRect(280, 590, 111, 26))
        self.SaveBooking.setObjectName("SaveBooking")
        self.Selectvehicle = QtWidgets.QLabel(parent=self.page_4)
        self.Selectvehicle.setGeometry(QtCore.QRect(150, 460, 131, 20))
        self.Selectvehicle.setObjectName("Selectvehicle")
        self.NextButton_2 = QtWidgets.QPushButton(parent=self.page_4)
        self.NextButton_2.setGeometry(QtCore.QRect(690, 590, 141, 26))
        self.NextButton_2.setObjectName("NextButton_2")
        self.vehicleTypeComboBox_2 = QtWidgets.QComboBox(parent=self.page_4)
        self.vehicleTypeComboBox_2.setGeometry(QtCore.QRect(150, 480, 75, 22))
        self.vehicleTypeComboBox_2.setObjectName("vehicleTypeComboBox_2")
        self.vehicleTypeComboBox_2.addItem("")
        self.vehicleTypeComboBox_2.addItem("")
        self.vehicleTypeComboBox_2.addItem("")
        self.vehicleTypeComboBox_2.addItem("")
        self.vehicleTypeComboBox_2.addItem("")
        self.BookingTypeComboBox_3 = QtWidgets.QComboBox(parent=self.page_4)
        self.BookingTypeComboBox_3.setGeometry(QtCore.QRect(690, 140, 121, 22))
        self.BookingTypeComboBox_3.setObjectName("BookingTypeComboBox_3")
        self.BookingTypeComboBox_3.addItem("")
        self.BookingTypeComboBox_3.addItem("")
        self.BookingTypeComboBox_3.addItem("")
        self.BookingTypeLabel = QtWidgets.QLabel(parent=self.page_4)
        self.BookingTypeLabel.setGeometry(QtCore.QRect(690, 120, 131, 20))
        self.BookingTypeLabel.setObjectName("BookingTypeLabel")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.page_4)
        self.calendarWidget.setGeometry(QtCore.QRect(690, 190, 256, 190))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_5 = QtWidgets.QLabel(parent=self.page_4)
        self.label_5.setGeometry(QtCore.QRect(720, 410, 49, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.bookingtime = QtWidgets.QLabel(parent=self.page_4)
        self.bookingtime.setGeometry(QtCore.QRect(690, 420, 91, 16))
        self.bookingtime.setObjectName("bookingtime")
        self.timeComboBox_4 = QtWidgets.QComboBox(parent=self.page_4)
        self.timeComboBox_4.setGeometry(QtCore.QRect(690, 440, 75, 22))
        self.timeComboBox_4.setObjectName("timeComboBox_4")
        self.timeComboBox_4.addItem("")
        self.timeComboBox_4.addItem("")
        self.timeComboBox_4.addItem("")
        self.timeComboBox_4.addItem("")
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.EnterSalePrice = QtWidgets.QLineEdit(parent=self.page_2)
        self.EnterSalePrice.setGeometry(QtCore.QRect(120, 340, 131, 22))
        self.EnterSalePrice.setObjectName("EnterSalePrice")
        self.VehicleSold = QtWidgets.QLabel(parent=self.page_2)
        self.VehicleSold.setGeometry(QtCore.QRect(120, 230, 71, 20))
        self.VehicleSold.setObjectName("VehicleSold")
        self.saleproce = QtWidgets.QLabel(parent=self.page_2)
        self.saleproce.setGeometry(QtCore.QRect(120, 320, 91, 16))
        self.saleproce.setObjectName("saleproce")
        self.SaleID = QtWidgets.QLabel(parent=self.page_2)
        self.SaleID.setGeometry(QtCore.QRect(120, 140, 81, 20))
        self.SaleID.setObjectName("SaleID")
        self.SaleAndSummary = QtWidgets.QLabel(parent=self.page_2)
        self.SaleAndSummary.setGeometry(QtCore.QRect(270, 30, 691, 51))
        self.SaleAndSummary.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"}")
        self.SaleAndSummary.setObjectName("SaleAndSummary")
        self.EnterSaleID = QtWidgets.QLineEdit(parent=self.page_2)
        self.EnterSaleID.setGeometry(QtCore.QRect(120, 160, 113, 22))
        self.EnterSaleID.setObjectName("EnterSaleID")
        self.Paymentmethod = QtWidgets.QLabel(parent=self.page_2)
        self.Paymentmethod.setGeometry(QtCore.QRect(600, 310, 111, 16))
        self.Paymentmethod.setObjectName("Paymentmethod")
        self.Customername_2 = QtWidgets.QLabel(parent=self.page_2)
        self.Customername_2.setGeometry(QtCore.QRect(600, 140, 91, 20))
        self.Customername_2.setObjectName("Customername_2")
        self.Customername = QtWidgets.QLineEdit(parent=self.page_2)
        self.Customername.setGeometry(QtCore.QRect(600, 160, 113, 22))
        self.Customername.setObjectName("Customername")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.page_2)
        self.dateEdit.setGeometry(QtCore.QRect(600, 250, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.vehicleIDlabel_4 = QtWidgets.QLabel(parent=self.page_2)
        self.vehicleIDlabel_4.setGeometry(QtCore.QRect(600, 230, 81, 20))
        self.vehicleIDlabel_4.setObjectName("vehicleIDlabel_4")
        self.vehicleSoldComboBox_4 = QtWidgets.QComboBox(parent=self.page_2)
        self.vehicleSoldComboBox_4.setGeometry(QtCore.QRect(120, 250, 91, 22))
        self.vehicleSoldComboBox_4.setObjectName("vehicleSoldComboBox_4")
        self.vehicleSoldComboBox_4.addItem("")
        self.vehicleSoldComboBox_4.addItem("")
        self.vehicleSoldComboBox_4.addItem("")
        self.vehicleSoldComboBox_4.addItem("")
        self.vehicleSoldComboBox_4.addItem("")
        self.paymentmethodsComboBox = QtWidgets.QComboBox(parent=self.page_2)
        self.paymentmethodsComboBox.setGeometry(QtCore.QRect(600, 330, 91, 22))
        self.paymentmethodsComboBox.setObjectName("paymentmethodsComboBox")
        self.paymentmethodsComboBox.addItem("")
        self.paymentmethodsComboBox.addItem("")
        self.paymentmethodsComboBox.addItem("")
        self.paymentmethodsComboBox.addItem("")
        self.clear = QtWidgets.QPushButton(parent=self.page_2)
        self.clear.setGeometry(QtCore.QRect(320, 590, 111, 26))
        self.clear.setObjectName("clear")
        self.Savesale = QtWidgets.QPushButton(parent=self.page_2)
        self.Savesale.setGeometry(QtCore.QRect(190, 590, 111, 26))
        self.Savesale.setObjectName("Savesale")
        self.back = QtWidgets.QPushButton(parent=self.page_2)
        self.back.setGeometry(QtCore.QRect(460, 590, 111, 26))
        self.back.setObjectName("back")
        self.ExitSystem = QtWidgets.QPushButton(parent=self.page_2)
        self.ExitSystem.setGeometry(QtCore.QRect(600, 590, 141, 26))
        self.ExitSystem.setObjectName("ExitSystem")
        self.contactnumber_3 = QtWidgets.QLineEdit(parent=self.page_2)
        self.contactnumber_3.setGeometry(QtCore.QRect(120, 420, 671, 91))
        self.contactnumber_3.setObjectName("contactnumber_3")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", "Password:"))
        self.label_4.setText(_translate("Form", "Vehicle Administration System"))
        self.label_7.setText(_translate("Form", "NDLOVU & XABA MOTORS"))
        self.label_8.setText(_translate("Form", "Password:"))
        self.label_9.setText(_translate("Form", "Password:"))
        self.label_10.setText(_translate("Form", "Password:"))
        self.label_2.setText(_translate("Form", "Username:"))
        self.VehicleManagement.setText(_translate("Form", "VEHICLE MANAGEMENT"))
        self.VehicleLineEdit.setText(_translate("Form", "Enter Vehicle ID"))
        self.RegistrationLabel.setText(_translate("Form", "Registration label"))
        self.EnterRegistration.setText(_translate("Form", "Enter registration"))
        self.makeLineEdit.setText(_translate("Form", "e.g. Toyota"))
        self.makeLabel.setText(_translate("Form", "Make"))
        self.modelLabel.setText(_translate("Form", "Model"))
        self.modelLineEdit.setText(_translate("Form", "e.g. Corolla"))
        self.yearLineEdit.setText(_translate("Form", "e.g. 2026"))
        self.yearLabel.setText(_translate("Form", "Year "))
        self.PriceLabel.setText(_translate("Form", "Price"))
        self.PriceLineEdit.setText(_translate("Form", "R0.00"))
        self.VehicletypeLabel.setText(_translate("Form", "Vehicle Type"))
        self.VehicleID_2.setText(_translate("Form", "Vehicle ID"))
        self.vehicleTypeComboBox.setItemText(0, _translate("Form", "New"))
        self.vehicleTypeComboBox.setItemText(1, _translate("Form", "Used"))
        self.vehicleTypeComboBox.setItemText(2, _translate("Form", "Demo"))
        self.AvailabilityLabel.setText(_translate("Form", "AvailabilityLabel"))
        self.AvailabilityComboBox.setItemText(0, _translate("Form", "Available"))
        self.AvailabilityComboBox.setItemText(1, _translate("Form", "Reserved"))
        self.AvailabilityComboBox.setItemText(2, _translate("Form", "Sold"))
        self.clearVehicleButton.setText(_translate("Form", "Clear"))
        self.saveVehicleButton.setText(_translate("Form", "Save Vehicle"))
        self.vehicleBackButton.setText(_translate("Form", "Back"))
        self.vehicleNextButton.setText(_translate("Form", "Next"))
        self.customerandbookingmanagement.setText(_translate("Form", "CUSTOMER & BOOKING MANAGEMENT"))
        self.VehicleIDLineEdit_2.setText(_translate("Form", "Enter Vehicle ID"))
        self.contactnumberLabel.setText(_translate("Form", "Contact Number"))
        self.fullnamelabel.setText(_translate("Form", "Full Name"))
        self.contactnumber.setText(_translate("Form", "Enter Contact Number"))
        self.VehicleID.setText(_translate("Form", "Vehicle ID"))
        self.fullname.setText(_translate("Form", "Enter Full Name"))
        self.Email.setText(_translate("Form", "Enter Email"))
        self.Emaillabel.setText(_translate("Form", "Email"))
        self.BookingBackButton_2.setText(_translate("Form", "Back"))
        self.clearVehicleButton_2.setText(_translate("Form", "Clear"))
        self.SaveBooking.setText(_translate("Form", "Save Booking"))
        self.Selectvehicle.setText(_translate("Form", "Select Vehicle"))
        self.NextButton_2.setText(_translate("Form", "Next"))
        self.vehicleTypeComboBox_2.setItemText(0, _translate("Form", "Toyota"))
        self.vehicleTypeComboBox_2.setItemText(1, _translate("Form", "Corolla"))
        self.vehicleTypeComboBox_2.setItemText(2, _translate("Form", "Volkswagen Polo"))
        self.vehicleTypeComboBox_2.setItemText(3, _translate("Form", "Hyundai i20"))
        self.vehicleTypeComboBox_2.setItemText(4, _translate("Form", "Ford Ranger"))
        self.BookingTypeComboBox_3.setItemText(0, _translate("Form", "Test Drive"))
        self.BookingTypeComboBox_3.setItemText(1, _translate("Form", "Vehicle Viewing"))
        self.BookingTypeComboBox_3.setItemText(2, _translate("Form", "Service Booking"))
        self.BookingTypeLabel.setText(_translate("Form", "Booking Type"))
        self.bookingtime.setText(_translate("Form", "Booking Time"))
        self.timeComboBox_4.setItemText(0, _translate("Form", "08:00 AM"))
        self.timeComboBox_4.setItemText(1, _translate("Form", "10:00 AM"))
        self.timeComboBox_4.setItemText(2, _translate("Form", "12:00 PM"))
        self.timeComboBox_4.setItemText(3, _translate("Form", "14:00 PM"))
        self.EnterSalePrice.setText(_translate("Form", "Enter sale price"))
        self.VehicleSold.setText(_translate("Form", "Vehicle Sold"))
        self.saleproce.setText(_translate("Form", "Sale Price"))
        self.SaleID.setText(_translate("Form", "Sale ID"))
        self.SaleAndSummary.setText(_translate("Form", "SALES & SUMMARY"))
        self.EnterSaleID.setText(_translate("Form", "Enter sale ID"))
        self.Paymentmethod.setText(_translate("Form", "Payement Method"))
        self.Customername_2.setText(_translate("Form", "Customer Name"))
        self.Customername.setText(_translate("Form", "Enter Customer Name"))
        self.vehicleIDlabel_4.setText(_translate("Form", "Sale Date"))
        self.vehicleSoldComboBox_4.setItemText(0, _translate("Form", "Toyota"))
        self.vehicleSoldComboBox_4.setItemText(1, _translate("Form", "Corolla"))
        self.vehicleSoldComboBox_4.setItemText(2, _translate("Form", "Volkswagen Polo"))
        self.vehicleSoldComboBox_4.setItemText(3, _translate("Form", "Hyundai i20"))
        self.vehicleSoldComboBox_4.setItemText(4, _translate("Form", "Ford Ranger"))
        self.paymentmethodsComboBox.setItemText(0, _translate("Form", "Cash\n"
"Bank"))
        self.paymentmethodsComboBox.setItemText(1, _translate("Form", "Transfer\n"
"Vehicle"))
        self.paymentmethodsComboBox.setItemText(2, _translate("Form", "Finance"))
        self.paymentmethodsComboBox.setItemText(3, _translate("Form", "Debit Card"))
        self.clear.setText(_translate("Form", "Clear"))
        self.Savesale.setText(_translate("Form", "Save Sale"))
        self.back.setText(_translate("Form", "Back"))
        self.ExitSystem.setText(_translate("Form", "Exit System"))
        self.contactnumber_3.setText(_translate("Form", "Sales Summary                                                                                                                                 Total Sales:  R0.00"))
